// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FibonacciSlicerClient is the client API for FibonacciSlicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibonacciSlicerClient interface {
	FibonacciSlice(ctx context.Context, in *FiboRequest, opts ...grpc.CallOption) (*FiboResponse, error)
}

type fibonacciSlicerClient struct {
	cc grpc.ClientConnInterface
}

func NewFibonacciSlicerClient(cc grpc.ClientConnInterface) FibonacciSlicerClient {
	return &fibonacciSlicerClient{cc}
}

func (c *fibonacciSlicerClient) FibonacciSlice(ctx context.Context, in *FiboRequest, opts ...grpc.CallOption) (*FiboResponse, error) {
	out := new(FiboResponse)
	err := c.cc.Invoke(ctx, "/proto.FibonacciSlicer/FibonacciSlice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FibonacciSlicerServer is the server API for FibonacciSlicer service.
// All implementations must embed UnimplementedFibonacciSlicerServer
// for forward compatibility
type FibonacciSlicerServer interface {
	FibonacciSlice(context.Context, *FiboRequest) (*FiboResponse, error)
	mustEmbedUnimplementedFibonacciSlicerServer()
}

// UnimplementedFibonacciSlicerServer must be embedded to have forward compatible implementations.
type UnimplementedFibonacciSlicerServer struct {
}

func (UnimplementedFibonacciSlicerServer) FibonacciSlice(context.Context, *FiboRequest) (*FiboResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FibonacciSlice not implemented")
}
func (UnimplementedFibonacciSlicerServer) mustEmbedUnimplementedFibonacciSlicerServer() {}

// UnsafeFibonacciSlicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibonacciSlicerServer will
// result in compilation errors.
type UnsafeFibonacciSlicerServer interface {
	mustEmbedUnimplementedFibonacciSlicerServer()
}

func RegisterFibonacciSlicerServer(s grpc.ServiceRegistrar, srv FibonacciSlicerServer) {
	s.RegisterService(&FibonacciSlicer_ServiceDesc, srv)
}

func _FibonacciSlicer_FibonacciSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FiboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonacciSlicerServer).FibonacciSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FibonacciSlicer/FibonacciSlice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonacciSlicerServer).FibonacciSlice(ctx, req.(*FiboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FibonacciSlicer_ServiceDesc is the grpc.ServiceDesc for FibonacciSlicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FibonacciSlicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FibonacciSlicer",
	HandlerType: (*FibonacciSlicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FibonacciSlice",
			Handler:    _FibonacciSlicer_FibonacciSlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fibonacci.proto",
}
